# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

export NPM_PACKAGES=$HOME/.npm-packages
export NODE_PATH=$HOME/.npm-packages/lib/node_modules

export PATH="/usr/local/opt/node@8/bin:$PATH"
export PATH=$HOME/.gem/ruby/2.3.0/bin:$PATH
export PATH=$HOME/.yarn/bin:$PATH
export PATH=$NPM_PACKAGES/bin:$PATH

export DISABLE_AUTO_TITLE="true"

